- name: install java
  yum:
    name: java-17-amazon-corretto.x86_64
    state: present

- name: install docker
  yum:
    name: docker
    state: present

- name: service start docker
  service:
    name: docker
    state: started

- name: copy war file work-station to host-2
  action: copy src=sample.war dest=/home/mayur
  notify:
    - run the container with tomcat
    - copy war file in tomcat-7 container
